"""Batch-oriented adapter for MAGNET."""
from __future__ import annotations

import ast
import importlib
from types import SimpleNamespace
from typing import Any, Dict, Mapping

import torch
from torch import Tensor, nn
import torch.nn.functional as F
from .defaults import model_parameters


MAGNET_FAMILY = "magnet"


def _as_namespace(values: Mapping[str, Any]) -> SimpleNamespace:
    return SimpleNamespace(**dict(values))


class MultiModel_Trainer(nn.Module):
    """Translate the common dataset batch into MAGNET calls."""

    def __init__(self, family: str, model: nn.Module, config: Mapping[str, Any]):
        super().__init__()
        self.family = family.lower()
        self.model = model
        self.config = dict(config)
        trainable_parameters = sum(
            parameter.numel()
            for parameter in self.model.parameters()
            if parameter.requires_grad
        )
        print(
            f"[MultiModel_Trainer] family={self.family} | "
            f"model={self.model.__class__.__name__} | "
            f"trainable_params={trainable_parameters:,}"
        )

    @classmethod
    def from_config(cls, config: Mapping[str, Any], magnet_args=None):
        family = str(config.get("family", "magnet")).lower()
        parameters = model_parameters(family, config.get("parameters", {}))

        if family != MAGNET_FAMILY:
            raise ValueError(
                f"Only model_family={MAGNET_FAMILY!r} is available; got {family!r}"
            )
        module = importlib.import_module("models.magnet")
        argument_values = vars(magnet_args).copy() if magnet_args else {}
        argument_values.update(parameters)
        args = _as_namespace(argument_values)
        model, _ = module.create_model(config.get("name", "MultiModel_X_light"), args)

        return cls(family, model, config)

    @property
    def is_magnet_family(self) -> bool:
        return self.family == MAGNET_FAMILY

    @classmethod
    def from_args(cls, args):
        raw_parameters = getattr(args, "model_parameters", "{}")
        if isinstance(raw_parameters, str):
            raw_parameters = (
                ast.literal_eval(raw_parameters) if raw_parameters.strip() else {}
            )
        if not isinstance(raw_parameters, Mapping):
            raise TypeError("model_parameters must be a dictionary")

        config = {
            "family": args.model_family,
            "name": args.MT_model_name,
            "parameters": dict(raw_parameters),
            "loss": args.model_loss,
            "find_unused_parameters": args.find_unused_parameters,
        }
        return cls.from_config(config, magnet_args=args)

    @staticmethod
    def prediction(output):
        return output[-1] if isinstance(output, (tuple, list)) else output

    def forward_image(self, x: Tensor, batch=None, output_size=None) -> Tensor:
        """Return a BCHW image generated by MAGNET coordinate queries."""
        batch = {} if batch is None else dict(batch)
        if output_size is None:
            output_size = x.shape[-2:]
        elif isinstance(output_size, int):
            output_size = (output_size, output_size)

        height, width = output_size
        ys = torch.linspace(-1 + 1 / height, 1 - 1 / height, height,
                            device=x.device, dtype=x.dtype)
        xs = torch.linspace(-1 + 1 / width, 1 - 1 / width, width,
                            device=x.device, dtype=x.dtype)
        yy, xx = torch.meshgrid(ys, xs, indexing="ij")
        coord = torch.stack((yy, xx), dim=-1).reshape(1, -1, 2).expand(x.shape[0], -1, -1)
        cell = torch.ones_like(coord)
        cell[..., 0] *= 2 / height
        cell[..., 1] *= 2 / width
        model_batch = {
            "inp": x, "coord": coord, "cell": cell,
            "prompt": batch.get("prompt", ["None", "None"]),
            "s_factor": batch.get("s_factor", torch.ones(x.shape[0], device=x.device)),
        }
        prediction = self.forward_batch(model_batch)["prediction"]
        return prediction.permute(0, 2, 1).reshape(x.shape[0], -1, height, width)

    def forward_batch(self, batch: Mapping[str, Any]) -> Dict[str, Tensor]:
        x = batch.get("inp", batch.get("lr"))
        if x is None:
            raise KeyError("Batch must contain 'inp' or 'lr'.")

        prompt = batch.get("prompt", ["None", "None"])
        self.model.gen_features(
            x=x,
            prompt_tensor=prompt,
            prompt_enable=bool(self.config.get("prompt_enable", False)),
            post_SR=bool(self.config.get("post_SR", False)),
            s_factor=batch["s_factor"],
            promptPD=batch.get("promptPD"),
        )
        query_chunk = int(self.config.get("query_chunk", 128**3))
        predictions = []
        for start in range(0, batch["coord"].shape[1], query_chunk):
            predictions.append(
                self.model.queries_values(
                    coord=batch["coord"][:, start : start + query_chunk],
                    cell=batch["cell"][:, start : start + query_chunk],
                )
            )
        output = torch.cat(predictions, dim=1)

        return {"prediction": self.prediction(output), "raw_output": output}

    def forward(self, batch: Mapping[str, Any], return_loss: bool = False):
        if return_loss:
            return self.training_step(batch)
        return self.forward_batch(batch)["prediction"]

    def training_step(self, batch: Mapping[str, Any]) -> Dict[str, Tensor]:
        result = self.forward_batch(batch)
        target = batch.get("gt", batch.get("hr"))
        if target is None:
            raise KeyError("Batch must contain 'gt', 'gts', or 'hr'.")

        prediction = result["prediction"]
        loss_name = str(self.config.get("loss", "l1")).lower()
        if loss_name == "mse":
            loss = F.mse_loss(prediction, target)
        elif loss_name == "l1":
            loss = F.l1_loss(prediction, target)
        else:
            raise ValueError(f"Unsupported loss: {loss_name}")
        result["loss"] = loss
        return result


class MultiModel_Trainner(MultiModel_Trainer):
    """Project-requested spelling of the unified trainer class."""
